### ISSUE TITLE
test.py fails

### ISSUE THREAD

**Issue by romusters** [dneprDroid/TFSecured#8]
-----------------------------------
Tests:
Using block size = 16
Hash of key="DJM2GUH7TPNCRU4NVEJXX7QJE3BDBH" is "b"\x9eP\xa5D\x95\xe1\x05p\x8b\xcc\xef'Q2\xf7\xd2\x14\x08F\xc5\x89\xfd\xa8\x93\x9f\xde`-\x13\x90\xe7\x90""
Some Text
Traceback (most recent call last):
  File "/home/robert/repositories/car-and-license-plate-detection/test.py", line 29, in <module>
    main()
  File "/home/robert/repositories/car-and-license-plate-detection/test.py", line 22, in main
    test()
  File "/home/robert/repositories/car-and-license-plate-detection/test.py", line 8, in testAES
    encrypted = cipher.encrypt(text)
  File "/home/robert/repositories/car-and-license-plate-detection/encrypt_model.py", line 28, in encrypt
    raw = self._pad(raw)
  File "/home/robert/repositories/car-and-license-plate-detection/encrypt_model.py", line 41, in _pad
    return s + str.encode((self.bs - len(s) % self.bs) * chr(self.bs - len(s) % self.bs))
TypeError: must be str, not bytes

**Comment by dneprDroid** [comment]
Hi @romusters ,
What python version and OS do you use?
And could you please provide your code for testing? I mean the rest part of your code in

```
File "/home/robert/repositories/car-and-license-plate-detection/test.py", line 8, in testAES
encrypted = cipher.encrypt(text)
```

(how did you load the string into `text ` variable from the file)

I've tested various byte strings for encryption using this code:

```python
    # test :
    key="DJM2GUH7TPNCRU4NVEJXX7QJE3BDBH"
    cipher = AESCipher(key)
    # example binary string 
    binary_str = b"\x9e\xa5\x95\xe1\x05\x8b\xcc\xef\xf7\xd2\x14\x08\xc5\x89\xfd\xa8\x93\x9f\xde\x13\x90\xe7\x90"
    print("\ntesting string `%s`\n" % binary_str)
    binary_str = cipher.encrypt(binary_str)
    print("[+] result: `%s`" % binary_str)
```

and it's working fine.
